packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'

allowBuilds:
  core-js: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - serialize-javascript@7.0.3 || 7.0.5
  - uuid@11.1.1

overrides:
  serialize-javascript@<=7.0.2: ^7.0.3
  serialize-javascript@>=5.0.0 <7.0.5: ^7.0.5
  uuid@<11.1.1: ^11.1.1
