name: docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        uses: ./.github/composite-actions/install

      - name: Build docs
        run: pnpm build:docs
